coverage:
  status:
    project:
      default:
        target: auto
        threshold: 15%
        base: auto 
        paths: 
          - "src"
        branches: 
          - main
        if_ci_failed: ignore
        informational: true
        only_pulls: false